### ISSUE TITLE
[BUG] 프런트엔드 패키지 설치 수행 시 shell 프로그램 대량 발생

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/vanilla-instagram#11]
**버그 설명**
* client 위치에서 npm i 수행 시 shell 프로그램이 대량으로 발생합니다. 원인 추측은 npm i 수행 시 뭔가가 걸리는거 같은데 그게 husky 인지는 잘 모르겠습니다.

**재현하기 위해**
* vanila-instagram/client 위치에서 npm i

**예상했던 결과**

**스크린샷**
![image](https://user-images.githubusercontent.com/50310464/127627010-f39c1411-f262-45a8-b360-5681ad1f6f85.png)

**추가 내용**
@bear-bear-bear

**Comment by will-kim-querypie** [comment]
VSCode와 Webstorm 모두에서
* npm i
* node_modules/ 를 삭제하고 npm i

를 수행했지만, 해당 문제가 발생하지 않았습니다. 상황을 좀 더 특정해주실 수 있나요?

**Comment by galaxy4276** [comment]
그저 npm i 일 뿐이라 더 특정할 수 있는 상황이 아니네요.
다른 분들 안 그런지 확인해봐야할 듯

**Comment by galaxy4276** [comment]
내 PC 문제
