### ISSUE TITLE
[FEATURE] 프런트 스크립트 접근 제어에 대한 아이디어

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/vanilla-instagram#25]
![npm](https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Npm-logo.svg/1200px-Npm-logo.svg.png)

* * *

**어떤 문제에 대한 기능 요청인지 설명**
* PM 으로 배치 된 @galaxy4276, @bear-bear-bear 가 프런트 개발자가 작업 중 난관을 겪거나 다양한 문제로 스크립트를 제어해야 할 상황이 올 것입니다.
* 해당 상황에 대해 코드는 동일하지만, 문제를 겪던 스크립트의 기능을 추상화한 함수 또는 인스턴스로 모듈화를 진행하는 솔루션을 요청합니다.

**원하는 솔루션 설명**
* 접근 제어할 기능 ( 파일 ) 에서 추상화시킨 함수를 작성해보기
* 함수를 테스트하고 따른 레포지토리 위치에서 모듈형태로 재작성하기
* npm 에 업데이트
* 프런트 개발자는 해당 모듈이 업데이트 됨을 인지하고 모듈에 대해 npm update 를 수행
* 프런트 개발자가 사용

> 예를 들어, 단 한줄의 함수에 대해 코드가 어떻게 작성되어있는 지 알 필요 조차 없이 프런트가 사용할 수 있음.
**💥기존에 잘 만들어진 라이브러리를 쓰면 안되나?**
> 프로젝트를 진행하면서 결론적으로 우리가 도움을 주고싶은 부분에 대한 추상적인 기능을 구현하는 것이 목적이며, 외부 라이브러리가 모든 문제를 유연하게 처리해줄거라는 보장이 없음

**추가 내용**
* 모든 에러나 난관을 외부도움으로 처리해주는 것이 아닌, 이 기능작업은 도움 없이 안되겠다 싶은 부분만을 프런트가 투명성있게 해결할 수 있게 끔 외부 모듈로 지원하자는  제안입니다.
* PM (작성자) 들은 함수의 원칙을 엄격하게 지켜 작성합니다. ( 한 가지 기능만, 알기 쉬운 이름, 이름 규칙 등 . )

**Comment by will-kim-querypie** [comment]
Looks good to me.

**Comment by galaxy4276** [comment]
https://www.npmjs.com/package/beargalaxy-sns
모듈 초안 작성되었습니다! 이용 가능

**Comment by galaxy4276** [comment]
작업 가능한 Git Repository 는 따로 초대 드렸습니다.

**Comment by galaxy4276** [comment]
다음 회의 때 설명, 모듈 적용 후 Close

**Comment by will-kim-querypie** [comment]
홀리쓋 ㅋㅋ 섹시해

**Comment by will-kim-querypie** [comment]
쓸 일이 없다면 가장 좋겠네
