### ISSUE TITLE
[BUG] 빌드에 관한 잠재적인 백엔드 버그 사항

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/vanilla-instagram#29]
**버그 설명**
현재 swc 문서에서는 path-alias 를 지원한다 명시되어 있으나,
swc 개발자 kdy1 유저분께서 개인 QnA 로 현재 내부 잠재적인 문제때문에 typescript 환경에서 path-alias 를 적용하지 못한다는 답변을 받았습니다.
현재 써머즈에서는 swc 를 회수하고, nodemon, ts-node 를 이용하여 해결을 본 상태이며, 현재 프로젝트에도 동일하게 적용 될 예정입니다.

**Comment by will-kim-querypie** [comment]
확인했습니다
