### ISSUE TITLE
[FEATURE] footer를 템플릿에서 block으로 설정한 문제

### ISSUE THREAD

**Issue by will-kim-querypie** [bear-bear-bear/vanilla-instagram#40]
**어떤 문제에 대한 기능 요청인지 설명**
---
auth-form 템플릿에서 공용 footer 포함할 때 단순 include 하면 되는데, 굳이 block으로 만들어서 페이지에서 반복 호출하게 함

![image](https://user-images.githubusercontent.com/57123802/129228304-c8104713-ac4a-4600-8aa8-f94335fa9183.png)

**원하는 솔루션 설명**
---
block footer를 include로 변경
<br>
**해당 솔루션 구현에 대해 고려해본 사항이 있나요?**

**추가 내용**

**Comment by pandora2948** [comment]
학생 ^^ 샷따 내려 ^^
