### ISSUE TITLE
[FEATURE] 현재 데이터베이스에 Seeder 구현해주세요.

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/vanilla-instagram#70]
어떤 문제에 대한 기능 요청인지 설명
---
<br>
Sequelize 기능을 이용해서 Database Seed 데이터를 작성해주세요.
프런트엔드, 백엔드 양 측간 테스트를 위해서 빠르게 추가해주는 것이 좋습니다.
<br>

추가 내용
---
[Sequelize Seed 사용하기](https://victorydntmd.tistory.com/41)

**Comment by will-kim-querypie** [comment]
User seeder had added at #71

**Comment by will-kim-querypie** [comment]
post seeder 등은 프론트 개발 진행도에 맞춰 천천히 추가될 예정입니다.
